### PR TITLE
Test py311 and support pydantic 2.0 and above

### PR DESCRIPTION
**Pull request by nabobalis**
Fixes https://github.com/Helioviewer-Project/python-api/issues/96

TODO:

- [x] Work out why some of the movie tests timeout
- [x] Work out why the screenshot return is not a URL
  - ```python
    ->           raise RuntimeError(res["error"])
    E           RuntimeError: unable to open image `/var/www/api.helioviewer.org/docroot/cache/events/2023/06/16/ivo%3A%2F%2Fhelio-informatics.org%2FAR_SPoCA_20230620_232600_20230616T180346_4.png': No such file or directory @ error/blob.c/OpenBlob/2874
    ```

- [x] Work out what source ID 37 is and add it.
   ```python
   >           assert source_id in enum_values
   E           assert 37 in [0, 1, 2, 3, 4, 5, ...]
   ```

### CODE REVIEW

**Comment by dgarciabriseno** [comment]
I made a PR to this CI branch, it fixes the test failures.

>  Work out why some of the movie tests timeout

There was some aggressive caching going on server side. So while the movies where done, the API would still return the cached status of "Queued" causing the test to time out when it shouldn't.

> Work out what source ID 37 is and add it.

This was IRIS which I recently added to HV.
My patch also includes data sources for new GONG images as well.

> Work out why the screenshot return is not a URL

This was another server side issue. the png it's claiming it can't find is a little highlighted active region that gets overlayed on the screenshot. The file was in the db but wasn't on disk. I'm not sure why this happened, but it should be fixed for this and all future screenshots.

**Comment by dgarciabriseno** [comment]
build_docs is still failing. Looks like it has to do with the pydantic 2.0 version bump

```
WARNING: Failed guarded type import with ImportError("cannot import name 'AbstractSetIntStr' from 'pydantic._internal._utils' (/home/runner/work/python-api/python-api/.tox/build_docs/lib/python3.11/site-packages/pydantic/_internal/_utils.py)")
```

**Comment by nabobalis** [comment]
Thanks, I will look into and patch it now.

**Comment by nabobalis** [comment]
That seems like a bug upstream in pydanatic. It only creates a warning which does not affect the final documentation build. 

I will try to see if I can replicate it in a simpler env and report upstream.

**Comment by nabobalis** [comment]
@dgarciabriseno Would you ok with doing a release of this, or shall I tag it?

Also I feel with the bump in pydanatic, a 1.1.0 version feels more appropriate?

**Comment by nabobalis** [comment]
I forgot to check if the release job requires the docs build to pass, if so we will need to change that and update the tagged commit.

**Comment by dgarciabriseno** [comment]
Yea it doesn't reach publish with docs build failing

**Pull request merged**
