### PR TITLE
typehinting package

### PR DESCRIPTION
**Pull request by nabobalis**
Adds a type hinting package for the docs instead of having to add them manually.

### CODE REVIEW

**Comment by nabobalis** [comment]
Testing out a new docs theme too.

**Comment by nabobalis** [comment]
This will need updating for the screenshots before merge.

**Comment by nabobalis** [comment]
Also do we like the new theme?

**Comment by akash5100** [comment]
> Also do we like the new theme?

Yes :)

**Comment by nabobalis** [comment]
I am going to merge this for now.

**Pull request merged**
